USE  HowKteam
GO
CREATE TABLE TEST
(
	ID INT IDENTITY(1,1), CharID AS 'WC' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	CONSTRAINT PK_TEST PRIMARY KEY(CharID)
)

INSERT INTO TEST DEFAULT VALUES
INSERT INTO TEST DEFAULT VALUES
INSERT INTO TEST DEFAULT VALUES