USE HowKteam
GO
SELECT GV.MAGV, HOTEN, NT.TEN FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE  GV.MAGV = NT.MAGV

SELECT * FROM GIAOVIEN WHERE LUONG = 2500

SELECT * FROM GIAOVIEN WHERE LUONG = 2500 AND MABM = 'HTTT'

--lay ra giao vien lon hon 40 tuoi

SELECT * FROM GIAOVIEN WHERE YEAR(GETDATE()) - YEAR(NGSINH) > 40

--lay ra ho ten, nam sinh va tuoi cua giao vien lon hon 40 tuoi
SELECT HOTEN, NGSINH, YEAR(GETDATE()) - YEAR(NGSINH) AS TUOI FROM GIAOVIEN WHERE YEAR(GETDATE()) - YEAR(NGSINH) > 40

--lay ra ma giao vien, ten giao vien va ten khoa giao vien do lam viec
SELECT GV.MAGV, GV.HOTEN, K.TENKHOA FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA

--lay ra giao vien la truong bo mon
SELECT GV.* FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--dem so luong 
SELECT COUNT(*) AS N'SO LUONG GV' FROM GIAOVIEN

--dem so luong nguoi than cua giao vien co ma gv la 007
SELECT COUNT(*) AS N'SO LUONG NGUOI THAN' FROM GIAOVIEN, NGUOITHAN
WHERE GIAOVIEN.MAGV = '007' AND GIAOVIEN.MAGV = NGUOITHAN.MAGV

--lay ra ten giao vien va ten de tai nguoi do tham gia
SELECT HOTEN, TENDT FROM GIAOVIEN, THAMGIADT, DETAI
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV AND DETAI.MADT = THAMGIADT.MADT

SELECT GIAOVIEN.HOTEN AS N'SL GIAO VIEN KHOA CNTT' FROM GIAOVIEN, KHOA, BOMON
WHERE BOMON.MABM = GIAOVIEN.MABM AND KHOA.MAKHOA = 'CNTT' AND BOMON.MAKHOA = KHOA.MAKHOA

SELECT GV.HOTEN FROM GIAOVIEN AS GV, THAMGIADT AS TG
WHERE GV.MAGV = TG.MAGV AND TG.KETQUA = N'Đạt'

SELECT * FROM GIAOVIEN 
WHERE HOTEN LIKE '%N%'

--co the thay Join = inner join
SELECT * FROM KHOA JOIN BOMON
ON BOMON.MAKHOA = KHOA.MAKHOA

SELECT * FROM BOMON FULL OUTER JOIN GIAOVIEN
ON BOMON.MABM = GIAOVIEN.MABM

--gan giong inner join
SELECT * FROM GIAOVIEN CROSS JOIN BOMON 