CREATE DATABASE LAB1
GO
USE LAB1
GO

CREATE TABLE LOAIMATHANG
(
	MaLoaiMatHang INT PRIMARY KEY,
	TenLoaiMatHang NVARCHAR(100)
)

CREATE TABLE KHACHHANG
(
	MaKhachHang INT PRIMARY KEY,
	MaKhuVuc INT,
	TenKhachHang NVARCHAR(100),
	TenCuaHang NVARCHAR(100),
	SoDTKhachHang NVARCHAR(100), 
	DiaChiEmail NVARCHAR(100),
	DiaChiNhanHang NVARCHAR(100)
)

CREATE TABLE DICHVU
(
	MaDichVu INT PRIMARY KEY,
	TenDichVu NVARCHAR(100),
)